In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv("2015-2024.csv")

In [3]:
data

,Code,Region,Name,A&E attendances Type 1 Departments - Major A&E,A&E attendances Type 2 Departments - Single Specialty,A&E attendances Type 3 Departments - Other A&E/Minor Injury Unit,A&E attendances Total attendances,"A&E attendances less than 4 hours from arrival to admission, transfer or discharge Type 1 Departments - Major A&E","A&E attendances less than 4 hours from arrival to admission, transfer or discharge Type 2 Departments - Single Specialty","A&E attendances less than 4 hours from arrival to admission, transfer or discharge Type 3 Departments - Other A&E/Minor Injury Unit",...,"A&E attendances greater than 4 hours from arrival to admission, transfer or discharge Total Attendances > 4 hours",Emergency Admissions Emergency Admissions via Type 1 A&E,Emergency Admissions Emergency Admissions via Type 2 A&E,Emergency Admissions Emergency Admissions via Type 3 and 4 A&E,Emergency Admissions Total Emergency Admissions via A&E,Emergency Admissions Other Emergency admissions (i.e not via A&E),Emergency Admissions Total Emergency Admissions,Emergency Admissions Number of patients spending >4 hours from decision to admit to admission,Emergency Admissions Number of patients spending >12 hours from decision to admit to admission,dates
0,NLW,NHS England South West,Bristol Community Health,0,0,4560,4560,0.0,0.0,4555.0,...,5,0,0,0,0,0,0,0,0,April-2018
1,RVJ,NHS England South West,North Bristol NHS Trust,7429,0,0,7429,6168.0,0.0,0.0,...,1261,2536,0,0,2536,1659,4195,373,0,April-2018
2,RA7,NHS England South West,University Hospitals Bristol NHS Foundation Trust,9569,2036,0,11605,7821.0,1922.0,0.0,...,1862,2985,9,0,2994,838,3832,396,0,April-2018
3,NLW,NHS England South West,Bristol Community Health,0,0,4839,4839,0.0,0.0,4832.0,...,7,0,0,0,0,0,0,0,0,April-2019
4,RVJ,NHS England South West,North Bristol NHS Trust,7934,0,0,7934,5532.0,0.0,0.0,...,2402,3183,0,0,3183,1772,4955,666,0,April-2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
261,RVJ,South Of England Commissioning Region,North Bristol NHS Trust,7049,0,0,7049,6241.0,0.0,0.0,...,808,2305,0,0,2305,1175,3480,307,0,September 2015
262,RA7,South Of England Commissioning Region,University Hospitals Bristol NHS Foundation Trust,8563,1768,0,10331,7708.0,1764.0,0.0,...,859,2725,13,0,2738,650,3388,293,0,September 2015
263,NLW,South Of England Commissioning Region,Bristol Community Health,0,0,5073,5073,0.0,0.0,4994.0,...,79,0,0,0,0,0,0,0,0,September 2016
264,RVJ,South Of England Commissioning Region,North Bristol NHS Trust,7329,0,0,7329,6135.0,0.0,0.0,...,1194,2598,0,0,2598,1247,3845,393,3,September 2016
265,RA7,South Of England Commissioning Region,University Hospitals Bristol NHS Foundation Trust,8753,1889,0,10642,7419.0,1875.0,0.0,...,1348,2712,15,0,2727,672,3399,347,1,September 2016

In [4]:
data['dates']

0          April-2018
1          April-2018
2          April-2018
3          April-2019
4          April-2019
            ...
261    September 2015
262    September 2015
263    September 2016
264    September 2016
265    September 2016
Name: dates, Length: 266, dtype: object

In [6]:
import pandas as pd

# Assuming 'data' contains your dataset and the dates are stored in a column named 'dates'

# Convert the 'dates' column to datetime format
data['dates'] = pd.to_datetime(data['dates'], format='%B %Y')

# Display the updated DataFrame
print(data['dates'])

ValueError: time data "April-2018" doesn't match format "%B %Y", at position 0. You might want to try:
    - passing `format` if your strings have a consistent format;
    - passing `format='ISO8601'` if your strings are all ISO8601 but not necessarily in exactly the same format;
    - passing `format='mixed'`, and the format will be inferred for each element individually. You might want to use `dayfirst` alongside this.

In [ ]:
data['year'] = data['dates'].dt.year

# Display the updated DataFrame
print(data['year'])

In [7]:


for column in data.columns[3:-2]:
    plt.figure(figsize=(15, 10))  # Adjust width and height as needed
    # Create line plot
    ax = sns.lineplot(data=data, x='dates', y=column, hue='Name')

    plt.xticks(rotation=90)  # Rotate the labels for better visibility
    
    ax.set_title(column + ' over time')
   


    # Show plot
    plt.show()

NameError: name 'df_emergency' is not defined

In [ ]:
data.columns[3:-2]

In [ ]:
correlation_matrix = data.iloc[:,3:-2].corr()
correlation_matrix